package com.mimacom.training.rest.api.impl;

import com.mimacom.training.rest.api.PetsApi;
import com.mimacom.training.rest.model.Pets;
import org.osgi.service.component.annotations.Component;


/**
 * Swagger Petstore
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
@Component(
        immediate = true
)
public class PetsApiServiceImpl implements PetsApi {
    /**
     * Create a pet
     *
     */
    public void createPets() {
        // TODO: Implement...
        
        
    }
    
    /**
     * List all pets
     *
     */
    public Pets listPets(Integer limit) {
        // TODO: Implement...
        
        return new Pets();
    }
    
    /**
     * Info for a specific pet
     *
     */
    public Pets showPetById(String petId) {
        // TODO: Implement...
        
        return null;
    }
    
}

